### ISSUE TITLE
Dynamic TimedCache

### ISSUE THREAD

**Issue by btv** [jaemk/cached#73]
First off, thank you for an awesome crate!
I'm trying to do something like the following:

```rust
pub fn fn_name(some_parameters, time: u64) -> Result<> {
 cached_key_result! {
            FN_NAME: TimedCache<> = TimedCache::with_lifespan_and_capacity(time, 10);
           fn inner(same_paramters_as_above) -> Result<> {
           ...code...
           }
  }
  inner(original_parameters)
}
```

But when I do, I get compiler errors that `time` isn't a `const`. I tried writing code to turn `time` into a `const`, but that never seemed to workout. So I'm wondering if its possible to have a more dynamic timer for TimedCache.

Thank you in advance.

**Comment by btv** [comment]
I've been trying to work on this in what little spare time I have. I did come across a non-const variable used in the current tests, I see these lines (https://github.com/jaemk/cached/blob/master/src/stores/timed.rs#L297)

```
        let init_capacity = 1;
        let mut c = TimedCache::with_lifespan_and_capacity(100, init_capacity);
```

So when I try to recreate them in my own codebase, I still get the same error:
```
cached_key_result! {
 SESSION_BY_ID: TimedCache<String, Session> = TimedCache::with_lifespan_and_capacity(1800,TIME);
    |                                                                                     ^^^^ non-constant value
```

I know its not your job to help me. And again, it seems like a problem on my side & not with the projects code . But any ideas on how I could help troubleshoot this would be greatly appreciated.

**Comment by btv** [comment]
Also, I can't seem to find where in the code these numbers need to be `const`. The only 2 lines in this repo that require that are [here](https://github.com/jaemk/cached/blob/9c9c103f59f1cb31575c30306fcd8af18e5d1e6f/src/lru_list.rs#L18)
```
impl<T> LRUList<T> {
    const FREE: usize = 0;
    const OCCUPIED: usize = 1;
```
but I'm still not sure where this requirement could be coming from.

**Comment by jaemk** [comment]
hey @btv, sorry I haven't had a chance to really look into this yet. My first thought is that because the cache macros all expand to an invocation of `once_cell::sync::Lazy` (basically a `lazy_static` block), having a variable value associated with the input that generates the contents of the "cell" is being flagged by the compiler. The cached macros themselves aren't like a memoized function - each callsite expands to _one_ unique memoized function, so passing a variable value to the macros would mean the expanded memoized function is dependent on the variable. Like you've noted, there's nothing related to the `TimedCache` type that requires a `const` time.

**Comment by btv** [comment]
Hi @jaemk, thank you for getting back to me I appreciate the explanation. If I'm understanding your correctly, it might still be possible for me to do what I'm trying to do, but I shouldn't use the macro to build the `TimedCache`. I'll should build it manually, like in the testing code.

**Comment by jaemk** [comment]
yes, that's correct

**Comment by btv** [comment]
I'm sorry I haven't said anything in over a month. Thank you for the confirmation.

**Comment by gitmalong** [comment]
@btv do you mind to share your solution for a creating a cache with a parameter based/dynamic TTL value?

**Comment by btv** [comment]
Hi @gitmalong, I'm sorry.  I no longer have access to the code,  so I can't share it with you. Best of luck in trying to recreate what I was thinking above.

**Comment by jaemk** [comment]
@gitmalong Two things
- The cache macros can't be passed variable params since they are really just expanding to lazy static blocks (the error @btv was hitting when the issue was opened)
- The `TimedCache` store doesn't have a method for "get from cache only if the key has been in the cache for under X seconds" -- the X seconds can only be set at cache construction time.

So to get what I think you're asking for, a `TimedCache` where you can apply a variable expiration time, there's two options:
- Add a method to `TimedCache`s impl, something like `get_cached_under_seconds(key, seconds)`
- Use the existing [`TimedCache::get_store`](https://github.com/jaemk/cached/blob/4d7dea23697488b54af28bd17904e53dcd05f07a/src/stores/timed.rs#L82) to access the underlying hashmap (`HashMap<K, (Instant, V)>`) where you can do a `.get(key)` to access the timestamped cached value that you can compare yourself.
Both of these options would require that you handle the memoization part yourself, e.g. you have to define the static cache and then write the logic for "get from cache or recompute" yourself:
```rust
// (mostly pseudo code)
lazy_static! { static ref CACHE = TimedCache::with_lifespan(30); }
fn do_thing(a: &str, b: &str) -> String {
  let key = (a.to_string(), b.to_string());
  if let Some((instant, value)) = CACHE.lock().unwrap().get(&key) {
      // check your custom time limit
      if (now - instant) < limit {
          return value.clone()
      }
  }
  let mut handle = CACHE.lock().unwrap();
  let new = recompute();
  handle.insert(key, (Instant::now(), new.clone()));
  new
```
